#! /bin/bash
[[ $0 != $BASH_SOURCE ]] && SCRIPT_PATH=$(realpath $BASH_SOURCE) || SCRIPT_PATH="`readlink -f "$0"`"
ENV_DIR="`dirname "$SCRIPT_PATH"`"

bash -rcfile <(echo "
  source ~/.bashrc
  source ${ENV_DIR}/../.albion/bin/activate
")

